// Types for Translation
export type Language = 'en' | 'ar';

export const CONTENT = {
    en: {
        nav: {
            home: 'Home',
            capabilities: 'Solutions',
            blog: 'Blog',
            legacy: 'About',
            work: 'Projects',
            whyUs: 'Why Us',
            contact: 'Contact',
            quote: 'Get Quote',
        },
        hero: {
            badge: 'Total Digital Transformation',
            title: 'FUSING INFRASTRUCTURE WITH SOFTWARE INTELLIGENCE',
            subtitle: 'From complex Cabling & Data Centers to advanced Enterprise ERP & Custom Software. We are the complete technology partner for your business growth.',
            ctaPrimary: 'Start Transformation',
            ctaSecondary: 'Our Work',
            scroll: 'Discover Services',
            infra: 'Infrastructure',
            secure: 'Cyber Security',
            dev: 'Odoo & Software',
            powered: 'Powered by Innovation',
        },
        services: {
            badge: 'End-to-End Solutions',
            titleStart: 'Complete',
            titleMiddle: 'Business',
            titleEnd: 'Ecosystem',
            titleLast: '',
            desc: 'We combine deep hardware expertise with modern software innovation. One provider for your Networks, ERP, Custom Software, and Security.',
            explore: 'Request Service',
            filterAll: 'All Solutions',
            filterSoft: 'Software & ERP',
            filterNet: 'Infrastructure',
            filterSec: 'Security',
        },
        process: {
            badge: 'How We Work',
            title: 'Our Engineering Process',
            desc: 'We follow a rigorous, agile methodology to ensure your infrastructure and software work in perfect harmony.',
        },
        cta: {
            title: 'Ready to Scale Your Enterprise?',
            desc: 'Stop managing multiple vendors. Partner with the one company that understands your bits, bytes, and business logic.',
            primary: 'Schedule Consultation',
            secondary: 'View Case Studies',
        },
        whyUs: {
            badge: 'The Integrated Advantage',
            title: 'Hardware Strength + Software Intelligence',
            desc: 'Why hire multiple vendors? We analyze your physical infrastructure and build the perfect software to run on it. From server racks to cloud deployment, we handle it all.',
            card1Title: 'Enterprise ERP Experts',
            card1Desc: 'Masters in implementing fully integrated ERP systems (Odoo & Custom) for manufacturing, retail, and service industries.',
            card2Title: '360° Infrastructure',
            card2Desc: 'We build the data centers that host your applications, ensuring 99.9% uptime and physical security.',
        },
        techOrbit: {
            title: 'Our Technology Stack',
            center: 'Core Tech',
        },
        portfolio: {
            badge: 'Success Stories',
            title: 'Delivered Projects',
            viewAll: 'View All Projects',
        },
        testimonials: {
            badge: 'Client Trust',
            title: 'What Our Partners Say',
        },
        partners: {
            text: 'Our Strategic Technology Partners',
        },
        contact: {
            title: 'Let\'s Build Your Future',
            subtitle: 'Have a project in mind? Whether it\'s cabling a new HQ or launching an E-commerce app, we are ready.',
            locationTitle: 'Headquarters',
            location: 'Cairo, Egypt',
            locationDesc: 'Operating Globally',
            emailTitle: 'Business Inquiries',
            emailDesc: 'hello@compuplus.cc',
            phoneTitle: 'Call / WhatsApp',
            phone: '02 2272 8010',
            phoneDesc: 'Available 9am - 6pm',
            secure: 'SSL ENCRYPTED',
            formName: 'Full Name',
            formEmail: 'Business Email',
            formMsg: 'Project Details',
            placeholderID: 'John Doe',
            placeholderEmail: 'name@company.com',
            placeholderMsg: 'I need an Odoo ERP system and Network installation...',
            btn: 'Send Request',
            successTitle: 'Message Sent',
            successMsg: 'We will analyze your request and get back to you shortly.',
            sending: 'Sending...',
        },
        footer: {
            desc: 'A unified technology powerhouse providing turnkey solutions: Network Infrastructure, Odoo ERP Implementation, Custom Software, and Security Systems.',
            capabilities: 'Our Solutions',
            company: 'Company',
            rights: 'All rights reserved.',
            privacy: 'Privacy Policy',
            terms: 'Terms of Service',
        },
    },
    ar: {
        nav: {
            home: 'الرئيسية',
            capabilities: 'حلولنا',
            blog: 'المدونة',
            legacy: 'من نحن',
            work: 'أعمالنا',
            whyUs: 'لماذا نحن',
            contact: 'تواصل معنا',
            quote: 'اطلب عرض سعر',
        },
        hero: {
            badge: 'تحول رقمي شامل',
            title: 'دمج البنية التحتية مع ذكاء البرمجيات',
            subtitle: 'من تمديد الشبكات ومراكز البيانات إلى حلول الـ ERP المتكاملة والبرمجيات الخاصة. نحن الشريك التكنولوجي المتكامل لنمو أعمالك.',
            ctaPrimary: 'ابدأ التحول الرقمي',
            ctaSecondary: 'سابقة الأعمال',
            scroll: 'اكتشف خدماتنا',
            infra: 'بنية تحتية',
            secure: 'أمن سيبراني',
            dev: 'برمجيات و Odoo',
            powered: 'مدعوم بالابتكار',
        },
        services: {
            badge: 'حلول من الألف للياء',
            titleStart: 'منظومة',
            titleMiddle: 'أعمال',
            titleEnd: 'متكاملة',
            titleLast: '',
            desc: 'نجمع بين خبرة الهاردوير العميقة وابتكار السوفتوير الحديث. مورد واحد لشبكاتك، نظام الـ ERP، البرمجيات الخاصة، والأمن.',
            explore: 'اطلب الخدمة',
            filterAll: 'جميع الحلول',
            filterSoft: 'البرمجيات و Odoo',
            filterNet: 'البنية التحتية',
            filterSec: 'الأنظمة الأمنية',
        },
        process: {
            badge: 'كيف نعمل',
            title: 'منهجية هندسية دقيقة',
            desc: 'نتبع منهجية علمية ورشيقة (Agile) لضمان أن تعمل بنيتك التحتية وبرمجياتك في تناغم تام.',
        },
        cta: {
            title: 'جاهز لتوسيع نطاق أعمالك؟',
            desc: 'توقف عن إدارة موردين متعددين. كن شريكاً للشركة الوحيدة التي تفهم أدق تفاصيل البنية التحتية ومنطق البرمجيات.',
            primary: 'احجز استشارة مجانية',
            secondary: 'شاهد قصص النجاح',
        },
        whyUs: {
            badge: 'الميزة التكاملية',
            title: 'قوة الهاردوير + ذكاء السوفتوير',
            desc: 'لماذا تتعامل مع عدة موردين؟ نحن ندمج بنيتك التحتية المادية مع الأنظمة البرمجية المثالية لها. من خزانة السيرفر وحتى الاستضافة السحابية.',
            card1Title: 'خبراء أنظمة الـ ERP',
            card1Desc: 'متخصصون في تنفيذ أنظمة تخطيط الموارد (Odoo وغيرها) للمصانع، التجزئة، والشركات الخدمية.',
            card2Title: 'بنية تحتية 360 درجة',
            card2Desc: 'نحن نبني مراكز البيانات التي تستضيف تطبيقاتك، مع ضمان استقرار وأمان فيزيائي كامل.',
        },
        techOrbit: {
            title: 'تقنيات نستخدمها',
            center: 'التقنيات',
        },
        portfolio: {
            badge: 'قصص نجاح',
            title: 'مشاريع تم تنفيذها',
            viewAll: 'عرض كل المشاريع',
        },
        testimonials: {
            badge: 'ثقة العملاء',
            title: 'شركاء النجاح يتحدثون',
        },
        partners: {
            text: 'شركاؤنا الاستراتيجيون في التكنولوجيا',
        },
        contact: {
            title: 'دعنا نبني مستقبلك',
            subtitle: 'لديك مشروع؟ سواء كان تجهيز مقر جديد بالشبكات أو إطلاق تطبيق متجر إلكتروني، نحن مستعدون.',
            locationTitle: 'المقر الرئيسي',
            location: 'القاهرة، مصر',
            locationDesc: 'نخدم عملاء عالميين',
            emailTitle: 'استفسارات الأعمال',
            emailDesc: 'رد خلال 24 ساعة',
            phoneTitle: 'اتصال / واتساب',
            phone: '02 2272 8010',
            phoneDesc: 'متاح من 9 صباحاً - 6 مساءً',
            secure: 'اتصال مشفر',
            formName: 'الاسم بالكامل',
            formEmail: 'بريد العمل',
            formMsg: 'تفاصيل المشروع',
            placeholderID: 'الاسم...',
            placeholderEmail: 'email@company.com',
            placeholderMsg: 'أحتاج نظام Odoo ERP وتجهيز شبكة داخلية...',
            btn: 'إرسال الطلب',
            successTitle: 'تم الإرسال',
            successMsg: 'سنقوم بتحليل طلبك والرد عليك في أقرب وقت.',
            sending: 'جاري الإرسال...',
        },
        footer: {
            desc: 'قوة تكنولوجية موحدة تقدم حلولاً تسليم مفتاح: البنية التحتية للشبكات، تنفيذ أنظمة Odoo ERP، البرمجيات الخاصة، والأنظمة الأمنية.',
            capabilities: 'حلولنا',
            company: 'الشركة',
            rights: 'جميع الحقوق محفوظة.',
            privacy: 'سياسة الخصوصية',
            terms: 'شروط الخدمة',
        },
    },
};
